# Generated by Django 3.2.12 on 2022-02-20 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('investment', models.CharField(max_length=200)),
                ('bankId', models.CharField(max_length=200)),
                ('type', models.CharField(max_length=200)),
                ('value', models.DecimalField(decimal_places=2, max_digits=8)),
                ('dueDate', models.DateTimeField()),
                ('profitability', models.DecimalField(decimal_places=2, max_digits=8)),
                ('risk', models.DecimalField(decimal_places=0, max_digits=3)),
                ('acquisitions', models.DateTimeField()),
                ('volumn', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
    ]
